### ISSUE TITLE
SSL connections with Steam

### ISSUE THREAD

**Issue by SR-dude** [Zeckmathederg/glfs#21]
I'm back trying to get this another shot.  I went through your book, checking for anything that I missed. There were a few things that I needed.  I'm confident I followed your advice correctly, as per the book. But still, I can't get steam to behave correctly.  I get these in my steam logs. So, I can't log in.

`src/common/opensslconnection.cpp (1624) : unable to load trusted SSL root certificates
`
...
`Download failed: http error 0 (client-update.akamai.steamstatic.com/steam_client_ubuntu12)`

I've tried some things. I've copied out of whole cloth, /etc/ssl, /usr/lib/ssl  & /usr/share/ca-certificates from ubuntu. I looked for a suggested certdata.txt for make-ca to try. Apparently ubuntu uses the one from the NSS package.
I did have some partial success in compiling openssl the debian way. I'll explain that one below.

`openssl version -a` gives `OPENSSLDIR: "/etc/ssl"` in GLFS but in ubuntu I get 
`compiler:...-DOPENSSL_TLS_SECURITY_LEVEL=2`
...
`OPENSSLDIR: "/usr/lib/ssl"`

So, I tried recompile openssl. Just this once I downgraded to openssl 3.0.15 and borrowed a configure line. That goes:
`../Configure shared --prefix=/usr  --openssldir=/usr/lib/ssl 
--libdir=lib/x86_64-linux-gnu  no-idea  no-mdc2  no-rc5  no-zlib 
 no-ssl3  enable-unit-test no-ssl3-method  enable-rfc3779 
enable-cms  no-capieng  no-rdrand  enable-ec_nistp_64_gcc_128`

Immediately, I had to recompile both curl and networkmanager to get my internet back on. But, once I did. I found that I can log into steam. But, I couldn't start a game. The command line output said it was something about the cloud. I also tweaked make-ca to dump its cert in /usr/lib/ssl, which it does not do by default. I have since reverted openssl.

I'd be interested in know your  output of `openssl version -a`. Also your source for `/etc/ssl/certdata.txt`. But, I have a hunch that this is going to be a tough one to solve. So, I'll listen to your advice and close this ticket. There is no need to get bogged down with this issue..

**Comment by zeckma-tech** [comment]
```
zeckma [~] > openssl version -a
OpenSSL 3.3.1 4 Jun 2024 (Library: OpenSSL 3.3.1 4 Jun 2024)
built on: Mon Jul  1 10:16:51 2024 UTC
platform: linux-x86_64
options:  bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -O2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DZLIB -DZLIB_SHARED -DNDEBUG
OPENSSLDIR: "/etc/ssl"
ENGINESDIR: "/usr/lib/engines-3"
MODULESDIR: "/usr/lib/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_ia32cap=0x7ed8320b078bffff:0x209c01a9
```

`certdata.txt` is from **make-ca** for me.

Per https://zeckmathederg.github.io/glfs/shareddeps/make-ca.html did you do:
```Bash
cat >> make-ca << "EOF"
ln -svf /etc/pki/tls/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt
EOF
```

This should work for the /etc/ssl OPENSSLDIR path. Got no issues for me and I haven't regenerated certs using **make-ca** in a month or two. It had no changes since then. So, the issue of it not finding certs probably comes down to the symlink `/etc/ssl/certs/ca-certificates.crt` not existing.

Also I will keep this issue open for now until it appears to not be a bug, but I won't tag this issue as I don't know if it's a bug yet.

**Comment by SR-dude** [comment]
WOW! You solved my problem. Somehow I missed that one. 

Steam shows that I'm missing  /usr/lib32/gio/modules/libdconfsettings.so. I am. I only have a 64-bit version.
But, that is a different problem. Off hand do you  know where the source for that is?  Closing.


/usr/lib/gio/modules/libdconfsettings.so: wrong ELF class: ELFCLASS64
Failed to load module: /usr/lib/gio/modules/libdconfsettings.so
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf66894b6
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf66873b2
src/vgui2/src/surface_linux.cpp (1954) : glXChooseVisual failed
src/vgui2/src/surface_linux.cpp (1954) : Fatal assert; application exiting

**Comment by zeckma-tech** [comment]
> /usr/lib/gio/modules/libdconfsettings.so: wrong ELF class: ELFCLASS64
Failed to load module: /usr/lib/gio/modules/libdconfsettings.so
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf66894b6
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf66873b2
src/vgui2/src/surface_linux.cpp (1954) : glXChooseVisual failed
src/vgui2/src/surface_linux.cpp (1954) : Fatal assert; application exiting

Did you compile Mesa and are you using the proprietary NVIDIA driver?

**Comment by SR-dude** [comment]
You're right. I recompiled mesa and it's all good. I had to use LD_PRELOAD to start games.

That's it then. It's all good. One reason why I  use LFS is to learn how things work. So, 
how did you come up with that symlink? Does gnutls generate that ca-bundle.crt?

**Comment by zeckma-tech** [comment]
I spent a good week or so trying to find out how to log in to Steam, and found that a certain file wasn't found on my LFS system at the time, but was there on my Arch system... And I knew what was "supposed" to generate it was **make-ca** but wasn't. So I checked if it could have been named to something else, something standard. Sure enough, yes it was, so I made the symlink to that file and magically Steam knew what to do.

Now I made an issue on the make-ca project and was turned down because making the symlink is non-standard and unnecessary for any BLFS package, but was the reason I was stumped for a week and probably made a good number of people at the time stop trying to get Steam working on LFS. So that fix is in GLFS.

And `/etc/pki/tls/certs/ca-bundle.crt` is generated by **make-ca**, `/etc/ssl/certs/ca-certificates.crt` is what Steam wants, so a simple symlink command added at the end of the **make-ca** script works fine.
