### ISSUE TITLE
Ubisoft Connect connectivity

### ISSUE THREAD

**Issue by SR-dude** [Zeckmathederg/glfs#22]
We need to find a friendlier crowd. Those LFS maintainers are too cranky. Where can someone go to discuss these problems ? perhaps discord?

**Comment by SR-dude** [comment]
Uplay/upc.exe is a 32-bit application. I've been reading the logs dumped by wine. Uplay is asking for both 32-bit Schannel and Kerberos. The difficulty is compiling 32-bit gnutls libs. It won't compile for me with gcc 13.
I can tell you that Connect works with Ubuntu. This build issue might need to be brought to the package
maintainers.

> int/sha3-shake.h:55:8: error: redefinition of 'struct sha3_128_ctx'
   55 | struct sha3_128_ctx {
      |        ^~~~~~~~~~~~
/usr/include/nettle/sha3.h:107:8: note: originally defined here
107 | struct sha3_128_ctx
>

**Comment by zeckma-tech** [comment]
> We need to find a friendlier crowd. Those LFS maintainers are too cranky. Where can someone go to discuss these problems ? perhaps discord?

I wouldn't say cranky but I think "cold" might be better, although even cold might not be fair, especially to most of the editors. I'd say most of them are chill. To be fair I feel like I have been getting more annoyed over time and I think they probably just go through a lot and have college/uni on the side. Won't assume their position, though. I don't like talking about them much because I feel slimy doing so. As for Discord, there are two servers for LFS I know, one I own and another that is more official: https://discord.gg/NqJ9c4zHYx and https://discord.gg/JqdWH8q respectively. I feel like the first server's people are more open-minded and less crap hits the fan there. Since I'm more comfy there, I am more open to helping people there but will help people in the other server as well. My personal Discord tag is just @zeckma if you feel more comfortable talking one-on-one. There is also an IRC for LFS on libera chat. I recall #lfs-support being the channel/room, whatever they call it.

> Uplay/upc.exe is a 32-bit application. I've been reading the logs dumped by wine. Uplay is asking for both 32-bit Schannel and Kerberos. The difficulty is compiling 32-bit gnutls libs. It won't compile for me with gcc 13.

For compiling 32-bit Nettle, it should theoretically go like:
```Bash
CC="gcc -m32" CXX="g++ -m32"         \
./configure --prefix=/usr            \
            --libdir=/usr/lib32      \
            --host=i686-pc-linux-gnu \
            --disable-static &&
make
```

And as the ***root*** user:
```Bash
make DESTDIR=$PWD/DESTDIR install
cp -Rv DESTDIR/usr/lib32/* /usr/lib32
cp -Rv DESTDIR/usr/include/* /usr/include
rm -rf DESTDIR
ldconfig
```

Then GnuTLS should possibly be a sort of normal 32-bit installation?? I'm not entirely sure. For Wine, I honestly sort of dipped at a point and let the user figure out how to go from there, to install more dependencies of Wine if they want or need them. I will probably add more dependencies for Wine in the book, and OFC 32-bit Nettle and GnuTLS.

Marking this issue as a bug and enhancement. Will probably work on it in the future. For now you could try launching whatever you are trying to launch via Steam's Proton by clicking the lower left button in the Steam library "Add a Game" -- do note that you will need to make a .desktop file for the specific .exe file you want to launch and point to that specific desktop file so Steam knows what to do, force it to be launched via Proton, and make sure it starts in the directory that has the .exe you want to launch. This is all stupid but could work for you, but depends on the complexity of the .exe you want to run and what it does. Stuff like Ubisoft and Battle.net is out of my pay grade.

**Comment by SR-dude** [comment]
My hunch is the private headers for nettle are tailored for 64-bit when installed. 
Thanks for your tips. You don't need to help me any further.
